#!/usr/bin/env bash
echo "Installing Angel Development Tools by Adrian Gjonca"
echo "To uninstall just delete the files:"

SCRIPT_DIR=$(dirname "$(realpath "$0")")

#Correct legacy install
rm -f /bin/angel-pc
rm -f /bin/angel-bd

#Main install section
mkdir -p "/usr/local/bin/"

echo "    /usr/local/bin/angel-pc"
cp "$SCRIPT_DIR""/Angel Precomp/angel-pc" "/usr/local/bin/angel-pc"
chmod +x "/usr/local/bin/angel-pc"

echo "    /usr/local/bin/angel-bd"
cp "$SCRIPT_DIR""/Angel Builder/angel-bd" "/usr/local/bin/angel-bd"
chmod +x "/usr/local/bin/angel-bd"

echo ""
